fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.8
    hooks:
      - id: clang-format
        types: [c++, c, header]
  - repo: local
    hooks:
      - id: go-vet
        name: go vet
        entry: ./tools/lint-go.sh
        language: script
        types: [go]
        files: ^tools/mrs-sdk-manager/
      - id: go-format-check
        name: go format
        entry: ./tools/format-go.sh --check
        language: script
        types: [go]
        files: ^tools/mrs-sdk-manager/
